name: tahoe_100_rl_gpu
channels:
  - pytorch
  - nvidia # Add nvidia channel for CUDA toolkit
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - datasets
  - ipykernel
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4 # <-- Updated to match the system module

